name: Build and Test
on:
  push:
  pull_request:
  release:
    types:
      - published
jobs:
  build:
    name: Build, Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: |
        go build ./...
    - name: Test
      run: |
        go test ./...